export const PROMOS_LIST_REQUEST = 'PROMOS_LIST_REQUEST'
export const PROMOS_LIST_SUCCESS = 'PROMOS_LIST_SUCCESS'
export const PROMOS_LIST_FAIL = 'PROMOS_LIST_FAIL'

export const PROMOS_CREATE_REQUEST = 'PROMOS_CREATE_REQUEST'
export const PROMOS_CREATE_SUCCESS = 'PROMOS_CREATE_SUCCESS'
export const PROMOS_CREATE_FAIL = 'PROMOS_CREATE_FAIL'
export const PROMOS_CREATE_RESET = 'PROMOS_CREATE_RESET'

export const PROMOS_DELETE_REQUEST = 'PROMOS_DELETE_REQUEST'
export const PROMOS_DELETE_SUCCESS = 'PROMOS_DELETE_SUCCESS'
export const PROMOS_DELETE_FAIL = 'PROMOS_LIST_FAIL'


